- .gitignore
- constraints.cabal
- src/Data/Constraint/Forall.hs
Changing `Forall*` from closed to open type families in order to make it
work on GHC 7.6. *Note*: I have actually only tested it on GHC 7.10.2
myself.
> Changing `Forall*` from closed to open type families

- src/Data/Constraint/Forall.hs
The now-polykinded `Forall` is capable of expressing both
`ForallF` and `ForallT` with a few helper classes. This
confines the "trusted" portion of the module to `inst`.
> Implement ForallF and ForallT in terms of Forall

- src/Data/Constraint/Forall.hs
Defining `ForallT` without explicit kind signatures
led to a loss of kind polymorphism. Adding such signatures
recovers it.
> Recover kind polymorphism

- src/Data/Constraint.hs
GHC-HEAD exports Any from GHC.Types instead of GHC.Prim as it was before.
See https://phabricator.haskell.org/D2049
Thankfully, GHC.Base seems to export Any in both versions.
So we import it from there.
Fixes #27
> fix build failure on GHC-HEAD (importing Any)

- src/Data/Constraint.hs
Change the type of `no` from `Bottom => Dict a` to
`Bottom => a`. There is no reason to limit it to producing
dictionaries, and it's easier to understand the latter as
"given `Bottom`, you can have anything."
> Generalize Bottom

- src/Data/Constraint/Deferrable.hs
Currently the parameters to `defer` and `deferEither` are in a different order:
```haskell
deferEither
:: forall {p :: Constraint} {proxy :: Constraint -> *} {r}.
Deferrable p =>
proxy p -> (p => r) -> Either String r
defer
:: forall {proxy :: Constraint -> *} {p :: Constraint} {r}.
Deferrable p =>
proxy p -> (p => r) -> r
```
With `TypeApplications` the order of `defer` should match `deferEither` which is more useful in my view
> Swap first arguments of ‘defer’ to match ‘deferEither’

- src/Data/Constraint.hs
This is a common pattern that I've found useful for everyday/practical usage of `Dict`.
Essentially lets you do things like:
~~~haskell
withDict d $ do
blah
blah
blah
~~~
and
~~~haskell
withDict d (some expression of sorts)
withDict d $ some expression of sorts
~~~
instead of
~~~haskell
case d of
Dict -> do
blah
blah
blah
~~~
and
~~~haskell
case d of
Dict -> some expression of sorts
~~~
At its surface, it's a "cosmetic" change, as one wouldn't have to explicitly pattern match on `Dict`, which saves an extra line and a level of indentation.
But, at a deeper level, it is a slick way of hiding the `Dict` constructor abstraction; one would be able to manipulate `Dict`s without ever using the `Dict` constructor, hiding away the constructor of the type as an implementation detail.  If the user …
> `withDict` continuation-style deconstructor for `Dict`

- src/Data/Constraint/Deferrable.hs
Added `AllowAmbiguousTypes` and renamed
```haskell
theDefer       ↦ defer_
theDeferEither ↦ deferEither_
```
> Add defer_ and deferEither_ that do not require proxy arguments.

- src/Data/Constraint/Nat.hs
- src/Data/Constraint/Symbol.hs
In [`magic`](https://github.com/ekmett/constraints/blob/0ed5c7cc8cd99e514ef5e995a7adaac9e2c10cdc/src/Data/Constraint/Nat.hs#L60), `Sub` expects a `Dict` but receives `id`, so things crash.
Here's a minimal test case exercising all 4 magic functions which now runs correctly.
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
import Data.Constraint.Nat
import Data.Constraint.Symbol
import Data.Proxy
import Data.Constraint
import GHC.TypeLits
main = do
case gcdNat @15 @20 of
Sub Dict -> print (natVal (Proxy :: Proxy (Gcd 15 20)))
case appendSymbol @"a" @"b" of
Sub Dict -> print (symbolVal (Proxy :: Proxy ("a" ++ "b")))
case takeSymbol @3 @"abcde" of
Sub Dict -> print (symbolVal (Proxy :: Proxy (Take 3 "abcde")))
case lengthSymbol @"abcde" of
Sub Dict …
> Fix magic functions in Nat and Symbol

- src/Data/Constraint.hs
* Update `Class` for AMP.
* Add `Bits`, `Natural`, and `Word`. There are still a lot of
`Int` and `Word` variants missing.
Fixes #48
> Add more Class and :=>

- src/Data/Constraint/Nat.hs
Previously maxCommutes had the same type as minCommutes and thus didn't
describe commutativity of Max.
> Fix maxCommutes.

- src/Data/Constraint/Nat.hs
The order of the variable types in associative axioms is changed. Also, the `axiom` is replaced by the `Dict` in some trivial cases.
> Reordering of the type variables

- src/Data/Constraint.hs
These instance are useful when enclosing `Dict`s in a data structure.
> Add NFData instances for Dict and (:-)

- CHANGELOG.markdown
- constraints.cabal
- src/Data/Constraint.hs
- src/Data/Constraint/Lifting.hs
In the next version of `base` (4.11), `Semigroup` will be a superclass of `Monoid`. This PR updates `constraints` accordingly.
> Adapt to the Semigroup-Monoid Proposal

- CHANGELOG.markdown
- src/Data/Constraint/Nat.hs
`base-4.11`+ (GHC 8.4+) introduced wired-in `Div` and `Mod` type families to `GHC.TypeLits`. Alas, these clash with the ones defined locally in `Data.Constraint.Nat`, so this PR takes the approach of simply reexporting the ones from `GHC.TypeLits` when a recent-enough `base` is used.
> Reexport Div/Mod from GHC.TypeLits (introduced in GHC 8.4)

- src/Data/Constraint.hs
I think `no :: Bottom => a` is sometimes useful like `absurd`.
> Export `no` (a method of Bottom)

- src/Data/Constraint/Nat.hs
Add axioms for plus and minus of natural numbers being inverse (some requiring a <= relationship between some of then numbers).
These three constraints were pulled from https://github.com/agda/agda-stdlib/blob/master/src/Data/Nat/Properties.agda#L1011-L1029
> Add axioms about plus and minus

- src/Data/Constraint/Nat.hs
This patch completes definitions of type families `Min` and `Max`, making GHC able to reason about them better. Before:
```
> :kind! Min 5 6
Min 5 6 :: GHC.Types.Nat
= Min 5 6
> :kind! Max 5 6
Max 5 6 :: GHC.Types.Nat
= Max 5 6
```
Now:
```
> :kind! Min 5 6
Min 5 6 :: GHC.Types.Nat
= 5
> :kind! Max 5 6
Max 5 6 :: GHC.Types.Nat
= 6
```
As a side effect, GHC becomes able to deduce `minZero` and `maxZero` on its own, without `axiom`.
> Complete definitions of Min and Max

- constraints.cabal
Pardon an automatically-posted pull request; this is a part of [Operation Vanguard](https://github.com/haskell-vanguard/haskell-vanguard). Note that this does not guarantee that tests and benchmarks are buildable.
> Support semigroups-0.19

- CHANGELOG.markdown
- constraints.cabal
- src/Data/Constraint.hs
- src/Data/Constraint/Deferrable.hs
Depend on the `type-equality` compatibility library so that `(:~~:)` may be used when compiling this library with GHC 8.0. This avoids having to redefine `(:~~:)` directly in the internals of `constraints` itself.
> Depend on type-equality to use (:~~:) on GHC 8.0

- src/Data/Constraint.hs
In non-Unicode locales, Haskell's character set handling means that if Haddock tries to print the list of undocumented symbols (even quietly as in `cabal new-build`) and comes across any unknown characters, the entire thing crashes.  This makes it go smoothly.
> Add Haddock for Unicode alias

- constraints.cabal
They are not needed on newer GHC.
> Depend on semigroups only on GHC < 8.0

- CHANGELOG.markdown
- constraints.cabal
- src/Data/Constraint/Symbol.hs
Also define `(++)` as a synonym for `AppendSymbol` and give it the same fixity as the term-level version of `(++)`. For the full details, see the `CHANGELOG` entry.
Fixes #100.
> Use AppendSymbol in Data.Constraint.Symbol

- CHANGELOG.markdown
- src/Data/Constraint.hs
This converts a quantified constraint into an entailment, as suggested in
https://github.com/ekmett/constraints/issues/41#issuecomment-403651598.
Fixes #41.
> Add implied

- constraints.cabal
- src/Data/Constraint/Lifting.hs
Remove instances for `ErrorT` and `ListT` (fixes #110).
_Not_ included:
- changelog
- version bump dependencies
> Remove instances for `ErrorT` and `ListT` (fixes #110)

- CHANGELOG.markdown
- src/Data/Constraint/Lifting.hs
Previously, all instances involving `ErrorT` and `ListT` were guarded with `!MIN_VERSION_transformers(0,6,0)`. This turns out not to be enough, however, as the instances involving classes from `mtl` also need to be guarded with `!MIN_VERSION_mtl(2,3,0)`. This is because while `mtl-2.3.*` does build with `transformers-0.5.*`, it does not provide instances for `ErrorT` or `ListT`, which could result in the build failures observed in #115.
Fixes #115.
> Guard `mtl`-related instances for `ErrorT`/`ListT` with appropriate CPP

- CHANGELOG.markdown
- src/Data/Constraint/Nat.hs
- src/Data/Constraint/Symbol.hs
- src/Data/Constraint/Unsafe.hs
The `axiom` definition was redundantly defined twice, once in `Data.Constraint.Nat` and once more in `Data.Constraint.Symbol`. This patch replaces these definitions with a single definition in `Data.Constraint.Unsafe`. Because `Data.Constraint.Unsafe` is exported, I renamed `axiom` to `unsafeAxiom` to reflect the existing naming conventions used in `Data.Constraint.Unsafe`.
> Move `axiom` to `Data.Constraint.Unsafe`, name it `unsafeAxiom`

- CHANGELOG.markdown
- src/Data/Constraint/Nat.hs
- src/Data/Constraint/Symbol.hs
- src/Data/Constraint/Unsafe.hs
This reduces the amount of code that has to be `unsafeCoerce`d down to just the `unsafeSNat` and `unsafeSSymbol` functions, which I have added to `Data.Constraint.Unsafe`. (If https://gitlab.haskell.org/ghc/ghc/-/issues/23478 were implemented, then we could do away with even those uses of `unsafeCoerce`.)
Fixes #114.
> Implement `Data.Constraint.{Nat,Symbol}`'s magic using `withKnown{Nat,Symbol}` when possible

- CHANGELOG.markdown
- constraints.cabal
- src/Data/Constraint/Char.hs
- src/Data/Constraint/Unsafe.hs
- tests/GH117Spec.hs
For now, this module only provides `charToNat` and `natToChar` operations, but we may include more operations in the future.
Fixes #117.
> Add `Data.Constraint.Char`
